Myversion
BohdanProkaza/Lab-8 pull request #1
Opened 2018-12-10 13:51 UTC by BohdanProkaza

@nechaido

2018-12-13 13:55 UTC, BohdanProkaza commented
Богдан Проказа ІП-82

2018-12-13 21:19 UTC, nechaido requested changes
Декомпозировать.

2018-12-17 07:41 UTC, BohdanProkaza commented
@nechaido виконав

2018-12-18 08:16 UTC, nechaido requested changes

2018-12-18 08:16 UTC, nechaido commented on ПР8.cpp
> +		for(int j=0;j<=narr;j++){
Зачем это цикл, если для условий задачи `i = j`?

2018-12-18 10:26 UTC, BohdanProkaza commented on ПР8.cpp
> +		for(int j=0;j<=narr;j++){
@nechaido виправив

2018-12-23 19:21 UTC, nechaido approved these changes

2018-12-23 21:46 UTC, merged